### ISSUE TITLE
pip 9.0 fail with puppetboard ?

### ISSUE THREAD

**Issue by KlavsKlavsen** [voxpupuli/puppet-puppetboard#174]
Running puppetboard (latest as of today - from git) - gives me these errors on a centos 7 server:

```
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/File[/srv/puppetboard/virtenv-puppetboard]/ensure: created
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns: New python executable in /srv/puppetboard/virtenv-puppetboard/bin/python
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns: Installing Setuptools..............................................................................................................................................................................................................................done.
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns: Installing Pip.....................................................................................................................................................................................................................................................................................................................................done.
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns: Running virtualenv with interpreter /bin/python
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns: 
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns: Usage:   
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:   pip install [options] <requirement specifier> ...
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:   pip install [options] -r <requirements file> ...
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:   pip install [options] [-e] <vcs project url> ...
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:   pip install [options] [-e] <local project path> ...
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:   pip install [options] <archive url/path> ...
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns: 
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns: no such option: --no-use-wheel
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns: Downloading/unpacking pip from https://pypi.python.org/packages/11/b6/abcb525026a4be042b486df43905d6893fb04f05aac21c32c638e939e447/pip-9.0.1.tar.gz#md5=35f01da33009719497f01a4ba69d63c9
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:   Running setup.py egg_info for package pip
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:     /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:       warnings.warn(msg)
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:     
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:     warning: no previously-included files found matching '.coveragerc'
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:     warning: no previously-included files found matching '.mailmap'
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:     warning: no previously-included files found matching '.travis.yml'
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:     warning: no previously-included files found matching '.landscape.yml'
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:     warning: no previously-included files found matching 'pip/_vendor/Makefile'
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:     warning: no previously-included files found matching 'tox.ini'
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:     warning: no previously-included files found matching 'dev-requirements.txt'
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:     warning: no previously-included files found matching 'appveyor.yml'
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:     no previously-included directories found matching '.github'
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:     no previously-included directories found matching '.travis'
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:     no previously-included directories found matching 'docs/_build'
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:     no previously-included directories found matching 'contrib'
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:     no previously-included directories found matching 'tasks'
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:     no previously-included directories found matching 'tests'
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns: Downloading/unpacking setuptools from https://pypi.python.org/packages/d5/b7/e52b7dccd3f91eec858309dcd931c1387bf70b6d458c86a9bfcb50134fbd/setuptools-34.3.3.zip#md5=696941b10b15f0717be957a4d6cfc12e
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:   Running setup.py egg_info for package setuptools
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:     Traceback (most recent call last):
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:       File "<string>", line 3, in <module>
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:       File "setuptools/__init__.py", line 12, in <module>
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:         import setuptools.version
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:       File "setuptools/version.py", line 1, in <module>
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:         import pkg_resources
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:       File "pkg_resources/__init__.py", line 70, in <module>
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:         import packaging.version
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:     ImportError: No module named packaging.version
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:     Complete output from command python setup.py egg_info:
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:     Traceback (most recent call last):
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns: 
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:   File "<string>", line 3, in <module>
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns: 
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:   File "setuptools/__init__.py", line 12, in <module>
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns: 
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:     import setuptools.version
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns: 
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:   File "setuptools/version.py", line 1, in <module>
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns: 
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:     import pkg_resources
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns: 
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:   File "pkg_resources/__init__.py", line 70, in <module>
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns: 
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns:     import packaging.version
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns: 
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns: ImportError: No module named packaging.version
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns: 
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns: ----------------------------------------
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns: Cleaning up...
Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns: Command python setup.py egg_info failed with error code 1 in /srv/puppetboard/virtenv-puppetboard/build/setuptools
```

**Comment by smaslennikov** [comment]
This seems to be related to https://github.com/stankevich/puppet-python/issues/365 and https://github.com/stankevich/puppet-python/issues/309

**Comment by smaslennikov** [comment]
@KlavsKlavsen I couldn't wait for PRs to get created and merged in puppet-python repo, so I forked puppetboard to depend on the currently functioning fork of puppet-python: https://github.com/smaslennikov/puppet-puppetboard . You can include it as a dependency in Puppetfile with:

```code
mod "smaslennikov/puppetboard",
  :git => "git@github.com:smaslennikov/puppet-puppetboard.git",
  :ref => "a9d3f5bfe978bfe7fae9d4482358345c656a717f"
```

**Comment by tux-o-matic** [comment]
@KlavsKlavsen in the current state of the Python module and especially if you're not going to be using Apache, you should just install Puppetboard, Gunicorn and supervisord via the Package type and the 'pip' provider. Combine that with the ini module and you can install and manage most things without outdated modules.

**Comment by gdubicki** [comment]
This issue is for Python 2 version of the Puppetboard so it is very outdated. I propose to close it.
